title: Yoann Betton
logo: "/images/PP_circled.png?raw=true"
description: > 
  <br><br>
  Data Science Student
  <br><br>
  Polytechnique Montréal / Université de Technologie de Compiègne 
  <br><br>
  Passionate about Sports, Motorsport, Sailing races, Science, Data, Technology, Engineering
  <br><br>
  <a href="https://www.linkedin.com/in/bettonyo/">View My LinkedIn Profile</a> 
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
