title: Yoann Betton
logo: "/images/PP_circled.png?raw=true"
description: > 
  <br><br>
  Data Science Student, Polytechnique Montréal / Université de Technologie de Compiègne
  <br><br>
  Passionate about Sports, Motorsport, Sailing races, Science, Data, Technology, Engineering
  <br><br>
  <a href="/pdf/BETTON_YOANN_CV.pdf" target="_blank">View my Curriculum Vitæ</a> 
  <br><br>
  <a href="https://www.linkedin.com/in/bettonyo/" target="_blank">View my LinkedIn profile</a>
  <br><br>
  <p style="font-size:11px">For any information, feel free to send me an email at yoann.betton[at]etu.utc.fr<a href="https://github.com/yoannbtn/yoannbtn.github.io">github.com/yoannbtn</a>.</p>
  
theme: jekyll-theme-minimal
# dark-theme: true
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
